import '../models/productModel.dart';

List<ProductModel> testProductList = [
  ProductModel(
      id: 21,
      name: "name of product",
      groupId: 2155,
      goodName: "goodName",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "fruto",
      barcode: "1111111111111111",
      expireDate: "21.06.2025",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "da",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "nya nya",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName aldhsfajkdghfadlkjsafhdjkajdfhkajdfh",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "f",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "a",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName:
          "goodName movenpick big name of good and again new row to check this",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName movenpick big name of good",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
  ProductModel(
      id: 21,
      name: "name",
      groupId: 2155,
      goodName: "goodName",
      typeId: 52,
      typeName: "typeName",
      brandId: 542,
      brandName: "brandName",
      barcode: "barcode",
      expireDate: "expireDate",
      fullGoodName: "fullGoodName",
      unitId: 2145,
      unitName: "unitName",
      quantity: 54,
      result: "result",
      forSale: "forSale"),
];